name: Deploy Admin

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install ADMIN dependencies
        run: |
          cd ADMIN
          npm install

- name: Build ADMIN
        run: |
          cd ADMIN
          npm run build
        env:
          NEXT_PUBLIC_SERVER_API_URL: https://ficxus.onrender.com/api/admin
          NEXT_PUBLIC_SERVICE1_HEALTH: https://main-server-69mo.onrender.com/api/health
          NEXT_PUBLIC_SERVICE2_HEALTH: https://auth-micro-service-eudw.onrender.com/health
          NEXT_PUBLIC_SERVICE3_HEALTH: https://fast-ml-server.onrender.com/health
          NEXT_PUBLIC_SERVICE4_HEALTH: https://url-shortener-rc3e.onrender.com/health
          NEXT_PUBLIC_SERVICE5_HEALTH: https://log-service-q7jb.onrender.com/health
          NEXT_PUBLIC_VAPID_PUBLIC_KEY: BMRqSYBeSZWP7kQMWW9SCri1z_NktCCJypKWlr8Hc7koSjWrOKu6cUnE1YvjpNz0N4e3hT2zyvDLtiBMD3I40gs

     - name: Upload build to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "ADMIN/.next,ADMIN/public,ADMIN/package.json,ADMIN/package-lock.json"
          target: "/var/www/admin/ADMIN"
          strip_components: 1

      - name: Restart on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /var/www/admin/ADMIN
            npm install --production
            pm2 restart admin || pm2 start npm --name "admin" -- start
            pm2 save
            echo "✅ Admin deployed!"